### ISSUE TITLE
Please update `npm` to avoid "write after end" bug

### ISSUE THREAD

**Issue by sparkleholic** [enactjs/enact-dev-dist#10]
Hi @JayCanuck , @webOS101 :
Please upgrade `npm` to `v6.1.1` under `node_binaries` to fix 'write after end' issue.
Please refer to the following links.
* npm: https://github.com/zkat/pacote/issues/142#issuecomment-391768600
* pacote: https://github.com/zkat/pacote/pull/151/files

**Comment by JayCanuck** [comment]
We have pulled the individual patches from `pacote`, `node-tar`,  and `minipass` to work around for the issue:
https://github.com/enactjs/enact-dev-dist/commit/dbb73a4d10ed69b7fbed74458c6ad85484b543e6
https://github.com/enactjs/enact-dev-dist/commit/b351bc3c0c013863bbe5d6b906b5ff9f3c7781d3
https://github.com/enactjs/enact-dev-dist/commit/181594c631e74caa96e023b16323d1d728033395

That said, clearly there are still some issues remaining, and as such, we do plan an update to NPM 6.x. Just want to verify no prominent side effects, like what affected us when we updated to NPM 5.x. :+1:

**Comment by sparkleholic** [comment]
Could you try this patch(https://github.com/zkat/pacote/pull/152)  too?

**Comment by JayCanuck** [comment]
Upgraded `webpack-3` branch to NPM 6.4.1 which includes all fixes. Closing out.
